---
- name: Configure VGA output
  lineinfile:
    path: '/boot/config.txt'
    regexp: "^{{ item.rsplit('=', 1)[0] }}="
    line: '{{ item }}'
  with_items:
  - 'display_rotate=1' # rotate 90deg counterclockwise
  - 'dtparam=audio=on'
  - 'dtparam=i2c_arm=off'
  - 'dtparam=i2s=off'
  - 'dtparam=spi=off'

- name: Configure console font
  lineinfile:
    path: '/etc/default/console-setup'
    regexp: "^{{ item.split('=', 1)[0] }}="
    line: '{{ item }}'
  with_items:
  - 'CHARMAP="UTF-8"'
  - 'CODESET="Lat15"'
  - 'FONTFACE="TerminusBold"'
  - 'FONTSIZE="12x24"'

- name: Configure console keyboard
  lineinfile:
    path: '/etc/default/keyboard'
    regexp: "^{{ item.split('=', 1)[0] }}="
    line: '{{ item }}'
  with_items:
  - 'XKBLAYOUT="dk"'

- name: Enable console-setup
  systemd:
    name: console-setup.service
    enabled: yes
    masked: no
    state: started
  when: not chroot
- name: '- when in chroot'
  command: systemctl enable console-setup.service
  when: chroot

# vim: set ts=2 sw=2 et:
